INSERT INTO creators (
      name, 
      username, 
      bio, 
      avatar_url, 
      whatsapp_number, 
      category, 
      location, 
      status,
      email,
      industry,
      video_portfolio,
      instagram_profile,
      tiktok_profile
    ) VALUES 
    (
        'Chiamaka okwara',
        'chiamakaokwara',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348180528673',
        'Lifestyle',
        'Nigeria',
        'active',
        'amynifemi@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMSRNG5wm/ https://vm.tiktok.com/ZMSRNgD1e/","https://vm.tiktok.com/ZMSRNg33r/"]'::jsonb,
        'https://www.instagram.com/p/DGWLkzBOKoq/?igsh=MWU3c3U2ZWlrczkzNQ==',
        'https://www.tiktok.com/@amyrights?_t=ZM-8wNLiMa0T6T&_r=1'
      ),
(
        'Samuel A. Oyebode m',
        'samuelaoyebodem',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348071166707',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Oyebodesamuel2019@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/C_P7nCUoq_R/?igsh=d2xsZG5ianVianV1","https://www.facebook.com/share/r/1AowpK34Zz/?mibextid=wwXIfr","https://www.instagram.com/reel/DFhTvOHoT2V/?igsh=MXFjMWx4c29kOHlrbA=="]'::jsonb,
        'https://instagram.com/saamu_eleja',
        'https://www.tiktok.com/@saamu_eleja?_t=ZM-8wNN3MKf5qJ&_r=1'
      ),
(
        'Fadeji Feyisola Fadeji',
        'fadejifeyisolafadeji',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349015597172',
        'Fashion',
        'Nigeria',
        'active',
        'oluwafeyiisola@gmail.com',
        'Fashion',
        '["https://www.instagram.com/reel/DJmenYTI8LL/?igsh=OGl4enU3a2w4MmVl","https://www.instagram.com/reel/DFdRDVJofx7/?igsh=MWx2bnYzbG90ejBoZQ==","https://www.instagram.com/reel/DEXwrjBIlFE/?igsh=emxnNXNmNnNjdXg5"]'::jsonb,
        'https://www.instagram.com/oluwafeyiisola?igsh=YzVkODRmOTdmMw==',
        'https://www.tiktok.com/@oluwafeyiisola?_r=1&_d=e9jmmfla6flae1&sec_uid=MS4wLjABAAAA-CqhtXUwWmOe5aJeh3vUzWghKcXAh7ejqb9Qrou8ku_0xjp4m0c0S4kr4HkYNG_M&share_author_id=6955155358462903301&sharer_language=en&source=h5_m&u_code=di8e99e9ick6d8&ug_btm=b0,b0&sec_user_id=MS4wLjABAAAA-CqhtXUwWmOe5aJeh3vUzWghKcXAh7ejqb9Qrou8ku_0xjp4m0c0S4kr4HkYNG_M&utm_source=copy&social_share_type=5&utm_campaign=client_share&utm_medium=ios&tt_from=copy&user_id=6955155358462903301&share_link_id=FF5DBD38-E7E0-4E07-A0AC-03436552D4A9&share_app_id=1233'
      ),
(
        'Philomena Maurice Bat',
        'philomenamauricebat',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348189729793',
        'Beauty',
        'Nigeria',
        'active',
        'mauricephilomena93@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRFPyXP/","https://vm.tiktok.com/ZMSRFY27c/","https://vm.tiktok.com/ZMSRFRgus/"]'::jsonb,
        'https://www.instagram.com/philanthas_signature?igsh=MXRtbml3b3J3MnBuYw==',
        'https://www.tiktok.com/@philantha0?_t=ZM-8wNNcCLFc0L&_r=1'
      ),
(
        'Shalom Aiyanna',
        'shalomaiyanna',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347019643886',
        'Beauty',
        'Nigeria',
        'active',
        'aiyannathereal@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DAdIWvDI1le/?igsh=NXhmMXJ2bzg4MHJ0","https://www.instagram.com/reel/C8uhGOnIK0x/?igsh=NXdkamtsdGlycWo5","https://www.instagram.com/reel/C7v6aHqIhdR/?igsh=MTFneHRuaGpibzY0Mw=="]'::jsonb,
        'https://www.instagram.com/shalomaiyanna?igsh=eDlpcnFsMW45cDg0&utm_source=qr',
        'https://www.tiktok.com/@shalomaiyanna4?_t=ZN-8wNNWluaiUY&_r=1'
      ),
(
        'Ezekiel Anyawema Happiness',
        'ezekielanyawemahappi',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348094567866',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'happinessezekiel09@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRF92hH/","https://vm.tiktok.com/ZMSRFxqt4/","https://vm.tiktok.com/ZMSRFvMq8/"]'::jsonb,
        'https://www.instagram.com/bar_happiness01?igsh=NzdnazdyOHFxcHdk&utm_source=qr',
        'www.tiktok.com/@bar_happiness'
      ),
(
        'Afolarin Wuraola',
        'afolarinwuraola',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348081795588',
        'Lifestyle',
        'Nigeria',
        'active',
        'afolarinwuraola@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMSRFw6hJ/ https://vm.tiktok.com/ZMSRFqwtE/  https://vm.tiktok.com/ZMSRFo26Q/"]'::jsonb,
        'https://www.instagram.com/wuraaaah?igsh=MTlkcWxwYm84aDF4dg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@wuraaagold?_t=ZM-8wNOjWzAodz&_r=1'
      ),
(
        'Emem Enoh Umoh',
        'ememenohumoh',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347063135953',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Emmyumoh06@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DBq9jg3NKYM/?igsh=MXV5ZXgwdWRmN3c0NA==","https://www.instagram.com/reel/DJMu2hwsHB_/?igsh=bGxyM2JqYnR5OGw=","https://www.instagram.com/reel/DGDjHSWoXub/?igsh=MThjYTUxMzEyd2ZlNQ=="]'::jsonb,
        'I''m on Instagram as @preti_emmy. Install the app to follow my photos and videos. https://www.instagram.com/invites/contact/?igsh=hw4mdgq5x6m9&utm_content=3fglm0f',
        'https://www.tiktok.com/@preti_emmy?_t=ZM-8wNRiRWYsL7&_r=1'
      ),
(
        'Olawunmi Temidayo',
        'olawunmitemidayo',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348105025068',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'olawunmitemidayovictor@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DIl07kpI4lM/?igsh=MXJ5MGlpMzBjaW50cA==","https://www.instagram.com/reel/DJOtTtQtYu1/?igsh=bnp0cDIyaThzOHR1","https://www.instagram.com/reel/DB-uMv_owIu/?igsh=MWMxYXdyNmwzcWNkbw=="]'::jsonb,
        'https://www.instagram.com/ogteamie?igsh=cGM1ZHk5eTM5YWh3&utm_source=qr',
        'https://www.tiktok.com/@ogteamie?_t=ZM-8wNTKXWNeWl&_r=1'
      ),
(
        'Terver Isaac Makurdi',
        'terverisaacmakurdi',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348119153997',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'tervermakurdi@gmail.com',
        'General/Personal Brand',
        '["3. ⁠https://youtube.com/shorts/h1J2eOIlTXk?si=1EcewS6W8c6YjxnD"]'::jsonb,
        'https://www.instagram.com/tervermakurdi?igsh=ZHJrdHVveDQzOTJo&utm_source=qr',
        'https://www.tiktok.com/@makurditerver'
      ),
(
        'Hannah Ogunnusi',
        'hannahogunnusi',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349012909259',
        'Lifestyle',
        'Nigeria',
        'active',
        'hogunnusi@gmail.com',
        'Lifestyle',
        '["https://www.instagram.com/reel/DI_p_eto3Lu/?igsh=YnF2bWl0aDlwa2xk","https://www.instagram.com/reel/DJb86ucqa9C/?igsh=YjVuaTZvMGwzanRm","https://www.instagram.com/reel/DJKK_sfKY3_/?igsh=OXFyNnVwejh2dm5r"]'::jsonb,
        'https://www.instagram.com/annie_nusi?igsh=MXh5cXRxZm5tcXE2eg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@annie_nusi_?_t=ZM-8wNVokknsyD&_r=1'
      ),
(
        'Oyekan Oluwamayowa',
        'oyekanoluwamayowa',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348149259392',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'oyekanoluwamayowawisdom@gmail.com',
        'General/Personal Brand',
        '["1) https://www.instagram.com/reel/DIwHYG_Cb36/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==","2) https://www.instagram.com/reel/DJEC9fAi8NQ/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==","3) https://www.instagram.com/reel/DFsap-Fu7Cu/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="]'::jsonb,
        'https://www.instagram.com/btr.gramm',
        'https://www.tiktok.com/@bragado_rhino'
      ),
(
        'Izzie Ekong',
        'izzieekong',
        'Content creator specializing in Health & Wellness. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348085329493',
        'Health & Wellness',
        'Nigeria',
        'active',
        'izzieekong@gmail.com',
        'Health & Wellness',
        '["https://vm.tiktok.com/ZMSRjcxXq/","https://vm.tiktok.com/ZMSR6e3op/","https://vm.tiktok.com/ZMSR6F7Rm/"]'::jsonb,
        'https://www.instagram.com/izzieekong?igsh=MWV4dXNkc2pybGdmOA%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@izzieekong?_t=ZM-8wNY84DhrXx&_r=1'
      ),
(
        'Akande Olayinka Heekmat',
        'akandeolayinkaheekma',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348076626537',
        'Lifestyle',
        'Nigeria',
        'active',
        'yimika4321@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZNdrLJ7jf/","https://vm.tiktok.com/ZNdrLNJB1/","https://vm.tiktok.com/ZNdr8whpr/"]'::jsonb,
        'https://www.instagram.com/yimikaa__a?igsh=bnN3cDRxeGhyZzln&utm_source=qr',
        'https://www.tiktok.com/@yimika.aaa?_t=ZN-8wNZyI2XuzO&_r=1'
      ),
(
        'Amiso Lucky Ibitamuno',
        'amisoluckyibitamuno',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349057695019',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'luckyamiso15@gmail.com',
        'General/Personal Brand',
        '["https://www.tiktok.com/@a.agencyofficial/video/7461329221151984901?is_from_webapp=1&sender_device=pc&web_id=7501613679088010757. https://www.instagram.com/reel/C6TyzW1o7IC/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==   https://www.instagram.com/reel/C_lWdwMI_L-/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="]'::jsonb,
        'https://www.instagram.com/_luckyai?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
        'https://www.tiktok.com/@_luckyai?is_from_webapp=1&sender_device=pc'
      ),
(
        'Olorunsuyi Deborah Aderonke',
        'olorunsuyideborahade',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348167802475',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'aderonkeolorunsuyi@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRMwbxb/","https://www.instagram.com/reel/DHg8kCSoKFP/?igsh=MW9qM25iczFndWkzYg=="]'::jsonb,
        'https://www.instagram.com/ronke_suyi?igsh=MW81NjEzdTYzc3c5&utm_source=qr',
        'https://www.tiktok.com/@ronke_suyi?_t=ZM-8wNcI5YOBde&_r=1'
      ),
(
        'Funmilayo Oginni',
        'funmilayooginni',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348119555812',
        'Beauty',
        'Nigeria',
        'active',
        'Sarahoginni13@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/C6vcZ-zIA3p/?igsh=eXZxYjZ5aXNraTgz","https://www.instagram.com/reel/DE2pPQ0ojs7/?igsh=MTMwcTZqd2NlaHp0bA==","https://www.instagram.com/reel/CvnHqBPo3li/?igsh=dmJyOTg4ZmNxbjMx"]'::jsonb,
        'https://www.instagram.com/_omopupa?igsh=MXBldjlkbmJ4Zm84NQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@_omopupa?_t=ZP-8wNdaLf7vzz&_r=1'
      ),
(
        'Akinyinka Mololuwa',
        'akinyinkamololuwa',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349139151744',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'jamesakinyinka@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRrc5Rs/"]'::jsonb,
        'https://www.instagram.com/directorcruizeee/profilecard/?igsh=MTBlaHBrZG9qbDg2bw==',
        'https://www.tiktok.com/@directorcruizeee?_t=ZM-8wNeBB6P4rd&_r=1'
      ),
(
        'Ayoola Oluwalonimi Emmanuel',
        'ayoolaoluwalonimiemm',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348103766194',
        'Beauty',
        'Nigeria',
        'active',
        'ayoolaoluwalonimi15@gmail.com',
        'Beauty',
        '["2.)https://www.instagram.com/reel/DF3sTgPoElZ/?igsh=cTI3ZnRxcjZvMWR1","3.) https://vm.tiktok.com/ZMSRrVQUD/"]'::jsonb,
        'https://www.instagram.com/itsloni__e?igsh=dHNpaTZ1aDR1aXN3&utm_source=qr',
        'https://www.tiktok.com/@itsloni__e?_t=ZM-8wNes3sEnkE&_r=1'
      ),
(
        'Victoria Nnadi',
        'victoriannadi',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348130112680',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'nnadivictoria16@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DINwY_xI_hv/?igsh=cnZrbHMwNHh2djBr","https://www.instagram.com/reel/DDg3_sJIEJG/?igsh=MXNrenU5amFjamhzbQ==","https://www.instagram.com/reel/DHWMT-vIRkf/?igsh=MW1zcTN0cHFwZTN2dg=="]'::jsonb,
        'https://www.instagram.com/victoriannadi__?igsh=OGd4ZzQ5MGR6dGUy',
        'Currently unavailable'
      ),
(
        'Jennipher Uwa',
        'jennipheruwa',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348181844705',
        'Beauty',
        'Nigeria',
        'active',
        'jennipherugc@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DJY-CBhoRNp/?igsh=MXBwbGEyN3M0bnU2Mg==","https://www.instagram.com/reel/DFLMa0pI44z/?igsh=MWlxMmdsYmdkcHh0OA==","https://www.instagram.com/reel/DIbyDUzoWh5/?igsh=MTlzNTN5NHJuaWc0dA=="]'::jsonb,
        'https://www.instagram.com/jennipheruwa',
        'https://www.tiktok.com/@jennipheruwa'
      ),
(
        'Ayomikun ogedengbe',
        'ayomikunogedengbe',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349015828858',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Theoilyskingirlie@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DHbOJM6iwMm/?igsh=MWhuZ2xmbW90amExaA==","https://www.instagram.com/reel/DHqtbB-ie1X/?igsh=ajN5YzlvZ2hmdzN0","https://www.instagram.com/reel/DHqtbB-ie1X/?igsh=ajN5YzlvZ2hmdzN0"]'::jsonb,
        'https://www.instagram.com/ayomikun__oged?igsh=ZXZwamoyeGUyZ25t&utm_source=qr',
        'https://www.tiktok.com/@ayomikun_oged?_t=ZN-8wNfwOWImvO&_r=1'
      ),
(
        'Rose Nneka',
        'rosenneka',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348137624291',
        'Lifestyle',
        'Nigeria',
        'active',
        'Workwithrosenneka@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMSRhtfLB/","https://vm.tiktok.com/ZMSRhfYK5/","https://vm.tiktok.com/ZMSRhXce5/"]'::jsonb,
        'https://www.instagram.com/the.rosennekaa?igsh=MTEwaHducmNpOG5wcg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@the.rosenneka?_t=ZM-8wNgDjaJes9&_r=1'
      ),
(
        'Oluwayomi  okani',
        'oluwayomiokani',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347085772362',
        'Beauty',
        'Nigeria',
        'active',
        'olooriadaeze@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DHBHup3sWIV/?igsh=c3NpNmtlMzV5cTho","https://www.instagram.com/reel/DDpBwvAt0RN/?igsh=MTQ3M3Y3bDZjbzcyeA==","https://www.instagram.com/reel/DHLUZ9ftrFn/?igsh=MWdqNWxqdzFqNnlqZA=="]'::jsonb,
        'https://www.instagram.com/_yormee?igsh=ZWsxZ2RlajQxYzZ0&utm_source=qr',
        'https://www.tiktok.com/@yormee_xx?_t=ZN-8wNgFoKJ2KE&_r=1'
      ),
(
        'Jennifer Chioma okoye',
        'jenniferchiomaokoye',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349161760748',
        'Beauty',
        'Nigeria',
        'active',
        'jenifferokonkwo096@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRhaduP/","https://vm.tiktok.com/ZMSRhaFSY/","https://vm.tiktok.com/ZMSRhCWYe/"]'::jsonb,
        'https://www.instagram.com/j.e.n.z.y_?igsh=N3ViY2RxeXIzc3Uz',
        'https://www.tiktok.com/@jenzy_ugc?_t=ZM-8wNgPhEF6v9&_r=1'
      ),
(
        'Augusta Raphael',
        'augustaraphael',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348000000000',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'augustaraphael8@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DHrAoLyt3Ax/?igsh=Y3VqZnh3eXEzZGZo","https://www.instagram.com/reel/DIBgh0VNOX0/?igsh=MXE3Yzl5ZWloMjdtcg==","https://www.instagram.com/reel/DH8WdbeNPSs/?igsh=NHQ5aHpybDB4Ym9q"]'::jsonb,
        'https://www.instagram.com/augustaraphael1?igsh=MWRrdjFkMzdtNzV6dg==',
        'https://www.tiktok.com/@augustaraphael?_t=ZM-8w9Sb2xHEVa&_r=1'
      ),
(
        'Ishaq Nana Ayiisha',
        'ishaqnanaayiisha',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348079874132',
        'Beauty',
        'Nigeria',
        'active',
        'nishabeautyandlifestyle@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DJcTFJwMP2O/?igsh=YzJ1NTdubXNpNnRo","https://www.instagram.com/reel/DJe3kQNMMap/?igsh=MXhsYjQ5OXJleWg1bQ==","https://www.instagram.com/reel/DJUlhD6srLa/?igsh=OWFoNnJidmtzb2F1"]'::jsonb,
        'https://www.instagram.com/nishas_life_diary?igsh=MTc4cDRjZ2F5N285Zg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@glowwithnisha?_r=1&_d=ek1hgh97hm598h&sec_uid=MS4wLjABAAAAuPDH0RX7owRS899X9IFb2Brpk6FQ2qcz_oOUWKSiaIE57A-_XQf5BBl-NnzTtpZm&share_author_id=7474711455595316230&sharer_language=en&source=h5_m&u_code=ej1l0ma60h6ihf&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAuPDH0RX7owRS899X9IFb2Brpk6FQ2qcz_oOUWKSiaIE57A-_XQf5BBl-NnzTtpZm&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7474711455595316230&share_link_id=42D1A9A3-6A5E-4689-8BEF-AE278DE2DD86&share_app_id=1233'
      ),
(
        'Osomo Divine',
        'osomodivine',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349030238984',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Divintumin@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DGiwb25NVo8/?igsh=a2MwNTExazc1MHli","https://www.instagram.com/reel/DEFfZXstZfG/?igsh=MnNkM2QwM2IwNGdv","https://www.instagram.com/reel/DHgDIOaNmuT/?igsh=MTY3d29jMjFvMWw3MA=="]'::jsonb,
        'https://www.instagram.com/shes_divine_?igsh=bmJhajR2NjN6eWlo&utm_source=qr',
        'https://www.tiktok.com/@divinestephen?_t=ZM-8wNgsSY0S62&_r=1'
      ),
(
        'Joyce Ewuzie',
        'joyceewuzie',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347082986377',
        'Beauty',
        'Nigeria',
        'active',
        'joyceewuzie.je@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZNdrL3swe/","https://vm.tiktok.com/ZNdrLgW8b/","https://vm.tiktok.com/ZNdrLTYtd/"]'::jsonb,
        'https://www.instagram.com/joicie.x?igsh=ZHNhMWk1bWZyaTN3&utm_source=qr',
        'https://www.tiktok.com/@chiamaka.bb?_t=ZN-8wNh7UazlEA&_r=1'
      ),
(
        'Chimamaka Favour',
        'chimamakafavour',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349044950747',
        'Beauty',
        'Nigeria',
        'active',
        'chimamakafavour640@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkkyq5/","https://vm.tiktok.com/ZMSRh3L2p/","https://www.instagram.com/reel/DJju1kDMLyx/?igsh=azdiOWRmNDZnbW5q"]'::jsonb,
        'https://www.instagram.com/chimaximum_?igsh=cXY4NWV0bWw4Zmh4&utm_source=qr',
        'https://www.tiktok.com/@chimaximum1?_t=ZM-8wNhIkMl0zO&_r=1'
      ),
(
        'Ehizele Ehimen',
        'ehizeleehimen',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349034125775',
        'Fashion',
        'Nigeria',
        'active',
        'theomohcreator@gmail.com',
        'Fashion',
        '["https://www.instagram.com/reel/DIt1mvOompF/?igsh=bnNoZ3B1MGcybG1j","https://www.instagram.com/reel/DHTtwpoIRvK/?igsh=MXA4NTZ0bXNqa3p3cw==","https://www.instagram.com/reel/DIwaT8pI-9F/?igsh=c3Ywc2wzbHU4MWRk"]'::jsonb,
        'https://www.instagram.com/theomoh_?igsh=OHBnNmVycG9qbm5v&utm_source=qr',
        'https://www.tiktok.com/@theomoh_?_t=ZS-8wNiFwXqu5B&_r=1'
      ),
(
        'Kanyinsola Akinbode',
        'kanyinsolaakinbode',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348128708194',
        'Beauty',
        'Nigeria',
        'active',
        'kanyinsolaakinbode@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkUcUu/","https://vm.tiktok.com/ZMSRksTew/","https://vm.tiktok.com/ZMSRkyyFX/"]'::jsonb,
        'https://www.instagram.com/kanyinsola_hannah?igsh=OGhsajFwcnF5Njh3&utm_source=qr',
        'https://www.tiktok.com/@lifestyle_of_hannah?_t=ZM-8tTlHNhexFd&_r=1'
      ),
(
        'Chimdinma Udeze',
        'chimdinmaudeze',
        'Content creator specializing in Technology. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348137834526',
        'Technology',
        'Nigeria',
        'active',
        'Ugcwithdrchim@gmail.com',
        'Tech',
        '["https://www.instagram.com/reel/DEomFkzIi4B/?igsh=b3ozZ2V3dzh3cmoz"]'::jsonb,
        'https://www.instagram.com/lifewith_drchim/profilecard/?igsh=YjJhcTB6ZmM4dHd5',
        'https://www.tiktok.com/@ugcwithdrchim_?_t=8mBiCdAaFHB&_r=1'
      ),
(
        'Melody Madu',
        'melodymadu',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349041897802',
        'Beauty',
        'Nigeria',
        'active',
        'Melodymadu7@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRk4Jpu/","https://vm.tiktok.com/ZMSRkU2VU/","https://vm.tiktok.com/ZMSRkHFLg/"]'::jsonb,
        'https://www.instagram.com/melly_theinfluencer?igsh=MTJlY2oxYW5yZGd4NQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@melly_theinfluencer?_t=ZM-8wNiZLUD6Qx&_r=1'
      ),
(
        'Chimdinma Udeze',
        'chimdinmaudeze1',
        'Content creator specializing in Health & Wellness. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348137834526',
        'Health & Wellness',
        'Nigeria',
        'active',
        'Ugcwithdrchim@gmail.com',
        'Health & Wellness',
        '[]'::jsonb,
        'https://www.instagram.com/lifewith_drchim/profilecard/?igsh=YjJhcTB6ZmM4dHd5',
        'https://www.tiktok.com/@ugcwithdrchim_?_t=8mBiCdAaFHB&_r=1'
      ),
(
        'Arogunbo Abisola',
        'arogunboabisola',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349069550982',
        'Beauty',
        'Nigeria',
        'active',
        'arogunboabisola@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkXaQk/","https://vm.tiktok.com/ZMSRkmRpg/","https://vm.tiktok.com/ZMSRkm3Lp/"]'::jsonb,
        'https://www.instagram.com/skincare_with_jb?igsh=emxzenA0Ymo2czdj&utm_source=qr',
        'https://www.tiktok.com/@abisola.josephine?_t=ZM-8wNilBVSVwE&_r=1'
      ),
(
        'Okikiola Alemu',
        'okikiolaalemu',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348021562005',
        'Lifestyle',
        'Nigeria',
        'active',
        'Theofficialdunnielambo@gmail.com',
        'Lifestyle',
        '["https://www.instagram.com/reel/DIq7_zHNhZs/?igsh=MWhoNTJqZTQ4cmYycg==","https://www.instagram.com/reel/DJRZ8TGNZr2/?igsh=MXJuZG0xNTZ3bTV0dg==","https://www.instagram.com/reel/DEMugkgtJv2/?igsh=eXV3c21wMjZiMTdr"]'::jsonb,
        'https://www.instagram.com/dunnielambo_/profilecard/?igsh=eTJyZHBvNjQ3aGdr',
        'https://www.tiktok.com/@babygirl4lifeeee?_r=1&_d=ejd143dhihl9bi&sec_uid=MS4wLjABAAAAfC_-PYbxATHmpkirdQG-eX8vwMEldZOvhItmtykztphpSeL4fhk1ZnwUUHW1JvlG&share_author_id=6953898589984080901&sharer_language=en&source=h5_m&u_code=di771f4bd37m39&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAfC_-PYbxATHmpkirdQG-eX8vwMEldZOvhItmtykztphpSeL4fhk1ZnwUUHW1JvlG&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=6953898589984080901&share_link_id=954093AA-4DEB-44FB-B43D-C7A69E7627E1&share_app_id=1233'
      ),
(
        'Sarah Oyadare',
        'sarahoyadare',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348084926600',
        'Beauty',
        'Nigeria',
        'active',
        'oyadaresarah@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkP18E/","https://vm.tiktok.com/ZMSRkmJQq/","https://vm.tiktok.com/ZMSRkPyem/"]'::jsonb,
        'https://www.instagram.com/iam.temitope0?igsh=eTF1MHJ1cXZ2Nmw5',
        'https://www.tiktok.com/@iam.temitope0?_t=ZM-8ti6yUaTLwD&_r=1'
      ),
(
        'Owoade Ololade',
        'owoadeololade',
        'Content creator specializing in Food. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348034554095',
        'Food',
        'Nigeria',
        'active',
        'chubzdfoodie@gmail.com',
        'Food',
        '["https://www.instagram.com/reel/DJR4QhaIlOu/?igsh=NG9jeXF6bDgzdzdz","https://www.instagram.com/reel/DHY3Kouo9Mt/?igsh=MTZ0cjdncWlpbzVhMg==","https://www.instagram.com/reel/DDUy3lgIcBi/?igsh=MWFnb2xoZDI3OXdkNg=="]'::jsonb,
        'https://www.instagram.com/chubzdfoodie?igsh=MWpjOHJteTB0amMzbA==',
        'https://www.tiktok.com/@chubzdfoodie?_t=ZM-8wNivHc0Qfm&_r=1'
      ),
(
        'Temiloluwa Akinleye',
        'temiloluwaakinleye',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349135311308',
        'Beauty',
        'Nigeria',
        'active',
        'gennyyy049@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkSGAG/","https://vm.tiktok.com/ZMSRk95Ty/","https://vm.tiktok.com/ZMSRkVFVx/"]'::jsonb,
        'https://www.instagram.com/_gennyy01?igsh=OG5tMzA3MGJya2Rt&utm_source=qr',
        'https://www.tiktok.com/@gennyy_01?_t=8oqLjQ4nbsc&_r=1'
      ),
(
        'Anna oluwatimilehin Akinwale',
        'annaoluwatimilehinak',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349034274151',
        'Beauty',
        'Nigeria',
        'active',
        'annalael29@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DIWhGu0RNFL/?igsh=cDBsbTc5eWRhb3Rx","https://www.instagram.com/reel/DIyrMyvpqbA/?igsh=NjFnZnM5aWR4dGtl","https://www.instagram.com/reel/DJbddoKxZEM/?igsh=MTViZDBhMnNxMThl"]'::jsonb,
        'https://www.instagram.com/_deannadiaries/profilecard/?igsh=dmM0MHdkdzk0cTJs',
        'https://www.tiktok.com/@_deannadiaries?_t=ZM-8tPmALTVSzN&_r=1'
      ),
(
        'Vivian Kerians',
        'viviankerians',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348134405719',
        'Beauty',
        'Nigeria',
        'active',
        'keriansv@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DJHmVMItrNA/?igsh=MWliM2R1YmVqN3cxaA==","https://www.instagram.com/reel/DIMeSsPtARz/?igsh=NHA1enVrbDBsdDJm","https://www.instagram.com/reel/DHiqSyVtnvr/?igsh=ajQ4YzlmOWNxOGZ2"]'::jsonb,
        'https://www.instagram.com/the5thguy?igsh=MThvMXU3dTdpajUxMg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@thebodyytemple?_t=ZM-8wNjGkyhd13&_r=1'
      ),
(
        'Omonor Emelda Ogboye',
        'omonoremeldaogboye',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348026875691',
        'Beauty',
        'Nigeria',
        'active',
        'omonorogboye@gmail.com',
        'Beauty',
        '["https://vt.tiktok.com/ZShxX484W/","https://vt.tiktok.com/ZShxX7YYX/","https://vt.tiktok.com/ZShxXVm4P/"]'::jsonb,
        'https://www.instagram.com/emeldaloveskincare',
        'https://www.tiktok.com/@emeldaloveskincare'
      ),
(
        'Hawau Alabi',
        'hawaualabi',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349069315982',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Hellohauwa@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DJoON2Ys5cE/?igsh=bzhvcDdweXpxM3N5","https://www.instagram.com/reel/DIgw75gsPw5/?igsh=OTJld3o2MnJ5ZTM1","https://www.instagram.com/reel/DHTCNWkMFMc/?igsh=MWFzMXJ6c2RjbmFh"]'::jsonb,
        'wwww.instagram.com/hellohauwa',
        'www.tiktok.com/hellohauwa'
      ),
(
        'Sandra jude Alegbe',
        'sandrajudealegbe',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347036691959',
        'Beauty',
        'Nigeria',
        'active',
        'Sandrathaddeusogbu@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/@skincaregirl_47/video/7488660652513332535?","https://vm.tiktok.com/ZMSRBNU5L/","https://vm.tiktok.com/ZMSRB8vMa/"]'::jsonb,
        'https://www.instagram.com/kosibeautyhub?igsh=MXFjcnMxOHY5aGp5aQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@skincaregirl_47?_r=1&_d=ek7leeli42ja98&sec_uid=MS4wLjABAAAAZD-w9Yq0zjyJmIbhX530G7SKopk6oWZFNN1DYhrK36yec9lbkSxlBPtVrk2e2tdZ&share_author_id=7436283581478241335&sharer_language=en&source=h5_m&u_code=eh7d9ij9bk7225&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAZD-w9Yq0zjyJmIbhX530G7SKopk6oWZFNN1DYhrK36yec9lbkSxlBPtVrk2e2tdZ&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7436283581478241335&share_link_id=379AE392-09B2-48C6-802E-6588C6545FA9&share_app_id=1233'
      ),
(
        'Bridget Adedayo',
        'bridgetadedayo',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348106443275',
        'Beauty',
        'Nigeria',
        'active',
        'adedayobridget71@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkvafk/","https://vm.tiktok.com/ZMSRBFWTc/","https://vm.tiktok.com/ZMSRkKvcB/"]'::jsonb,
        'https://www.instagram.com/themultifacetednurse_?igsh=MXBoZXViN3k3dDJ0Zw==',
        'tiktok.com/@themultifacetednurse'
      ),
(
        'Hajara Muhammad Hassan',
        'hajaramuhammadhassan',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349018156086',
        'Beauty',
        'Nigeria',
        'active',
        'Hassanhajara07@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRkvtaE/","https://vm.tiktok.com/ZMSRkoHKR/","https://vm.tiktok.com/ZMSRB8fnP/"]'::jsonb,
        'https://www.instagram.com/@Mrdhajjo',
        'https://www.tiktok.com/@mrdhajjo.ugc?_t=ZM-8sxMNdvJ2sI&_r=1'
      ),
(
        'Miracle Ivarah',
        'miracleivarah',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349045158959',
        'Beauty',
        'Nigeria',
        'active',
        'miracleivarah@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/@mimeeugcofficial/video/7501720490529148166?_r=1&u_code=ej9cljg5d25lkm&preview_pb=0&sharer_language=en&_d=ehhci8akd203ml&share_item_id=7501720490529148166&source=h5_m&timestamp=1747331107&user_id=7481998704691020818&sec_user_id=MS4wLjABAAAA1QsXJpRKaLL97gO3dG_buiFctZRA1gNgDvYri1U9jwH-9edff_m6rpUWe3lGszIY&social_share_type=0&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7493915638534145847&share_link_id=f8b65597-7422-456f-9106-cea443236b22&share_app_id=1233&ugbiz_name=MAIN&ug_btm=b8727%2Cb2878&link_reflow_popup_iteration_sharer=%7B%22click_empty_to_play%22%3A1%2C%22dynamic_cover%22%3A1%2C%22follow_to_play_duration%22%3A-1.0%2C%22profile_clickable%22%3A1%7D&enable_checksum=1","https://vm.tiktok.com/ZMSRBjWyT/","https://vm.tiktok.com/ZMSRktTxH/"]'::jsonb,
        'https://www.instagram.com/mimeeugcofficial?igsh=MWtnOG41MTl1cnN0Ng==',
        'https://www.tiktok.com/@mimeeugcofficial?_r=1&_d=ehhci8akd203ml&sec_uid=MS4wLjABAAAA1QsXJpRKaLL97gO3dG_buiFctZRA1gNgDvYri1U9jwH-9edff_m6rpUWe3lGszIY&share_author_id=7481998704691020818&sharer_language=en&source=h5_m&u_code=ej9cljg5d25lkm&timestamp=1747331012&user_id=7481998704691020818&sec_user_id=MS4wLjABAAAA1QsXJpRKaLL97gO3dG_buiFctZRA1gNgDvYri1U9jwH-9edff_m6rpUWe3lGszIY&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7493915638534145847&share_link_id=33eb86ad-a477-484b-bb90-8fe47f316e34&share_app_id=1233&ugbiz_name=ACCOUNT&ug_btm=b8727%2Cb7360&social_share_type=5&enable_checksum=1'
      ),
(
        'Zin Martins',
        'zinmartins',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348105603621',
        'Beauty',
        'Nigeria',
        'active',
        'zinzinn2122@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZNdrNeSkw/","https://www.instagram.com/reel/DI4IcF2oDo0/?igsh=aTV0ZDVmeXhhODU=","https://vm.tiktok.com/ZNdrNMhfH/"]'::jsonb,
        'https://www.instagram.com/oops.chainaaa?igsh=MTM0OHltMTI4cDBwMg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@oops.chainaaa?_t=ZN-8wNkNVHgRja&_r=1'
      ),
(
        'Confidence CHIKAMSO',
        'confidencechikamso',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348149076477',
        'Beauty',
        'Nigeria',
        'active',
        'Kamsobrandcollab@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/@kamso_ugc_creator/video/7502389897114799365?_r=1&u_code=edhj0bf59c94ej&preview_pb=0&sharer_language=en&_d=ec4aabki0e9666&share_item_id=7502389897114799365&source=h5_m&timestamp=1747331495&utm_source=copy&tt_from=copy&enable_checksum=1&utm_medium=ios&share_link_id=B48CFA68-895F-452C-9661-29F2F09DA18F&user_id=7358384967619200005&sec_user_id=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&social_share_type=0&ug_btm=b8727"]'::jsonb,
        'https://www.tiktok.com/@kamso_ugc_creator?_r=1&_d=ec4aabki0e9666&sec_uid=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&share_author_id=7358384967619200005&sharer_language=en&source=h5_m&u_code=edhj0bf59c94ej&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7358384967619200005&share_link_id=1A413398-6D89-47BE-85BA-3F92A8A9EBD2&share_app_id=1233',
        'https://www.tiktok.com/@kamso_ugc_creator?_r=1&_d=ec4aabki0e9666&sec_uid=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&share_author_id=7358384967619200005&sharer_language=en&source=h5_m&u_code=edhj0bf59c94ej&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7358384967619200005&share_link_id=1A413398-6D89-47BE-85BA-3F92A8A9EBD2&share_app_id=1233'
      ),
(
        'Febisola iris',
        'febisolairis',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349022640842',
        'Beauty',
        'Nigeria',
        'active',
        'Justiris23@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRBrD6Y/","https://vm.tiktok.com/ZMSRBaVyx/","https://vm.tiktok.com/ZMSRBx1PX/"]'::jsonb,
        'https://www.instagram.com/lvy_lane_?igsh=Z3VlOWpudGNidmpn&utm_source=qr',
        'https://www.tiktok.com/@febisola_iris?_t=ZM-8wNkikUfs2B&_r=1'
      ),
(
        'Udeh Favour',
        'udehfavour',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347061723947',
        'Beauty',
        'Nigeria',
        'active',
        'favourudeh019@gmail.com',
        'Beauty',
        '[]'::jsonb,
        'https://www.instagram.com/invites/contact/?igsh=10sf1oc3onhe4&utm_content=y4fl649',
        'https://www.instagram.com/invites/contact/?igsh=10sf1oc3onhe4&utm_content=y4fl649'
      ),
(
        'Mary Abraham Udoh',
        'maryabrahamudoh',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348108643796',
        'Beauty',
        'Nigeria',
        'active',
        'abrahamary922@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRBmXxv/","https://vm.tiktok.com/ZMSRBqKhh/","https://www.instagram.com/reel/DIBc8OAorNe/?igsh=MWNxMmJncGdzeWhobQ=="]'::jsonb,
        'https://www.instagram.com/moments_with._mae_ugc?igsh=NjNjcTF0ZXhxOHkz&utm_source=qr',
        'https://www.tiktok.com/@maemoments__?_t=ZM-8wNl5yDqA6h&_r=1'
      ),
(
        'Adebola Precious Adeboye',
        'adebolapreciousadebo',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348085164398',
        'Beauty',
        'Nigeria',
        'active',
        'bolascrib@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRBBYGb/","https://vm.tiktok.com/ZMSRBu6WE/","https://vm.tiktok.com/ZMSRBVk7S/"]'::jsonb,
        'https://www.instagram.com/bo._la?igsh=NzVsNmlmdjdhdTdx&utm_source=qr',
        'https://www.tiktok.com/@bolas.crib?_t=ZM-8wNlaas7jHB&_r=1'
      ),
(
        'Chizoba Gift Amaefula',
        'chizobagiftamaefula',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349032504880',
        'Beauty',
        'Nigeria',
        'active',
        'Cleopatraamaefula@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZNdrNAstT/","https://vm.tiktok.com/ZNdrNMu6X/","https://vm.tiktok.com/ZNdrNd7yc/"]'::jsonb,
        'https://www.instagram.com/cleopatra_amaefula?igsh=NzBuM2tzZWZjaWdm&utm_source=qr',
        'https://www.tiktok.com/@cleopatras.update?_t=ZN-8wNlxVsf7V0&_r=1'
      ),
(
        'Maryam Muhammed Hassan',
        'maryammuhammedhassan',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348165336918',
        'Beauty',
        'Nigeria',
        'active',
        'marymhassn.ugc@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRBng46/","https://vm.tiktok.com/ZMSRSLx3m/","https://vm.tiktok.com/ZMSRBGVxq/"]'::jsonb,
        'https://www.instagram.com/mrym_hassn_?igsh=MWZ6Znh0cWpvaXQ4Yg==',
        'https://www.tiktok.com/@marym_hassn.ugc'
      ),
(
        'Boluwatife Badru',
        'boluwatifebadru',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348103228559',
        'Fashion',
        'Nigeria',
        'active',
        'badruboluwatife24@gmail.com',
        'Fashion',
        '["https://www.instagram.com/reel/C_VO636I5Jm/?igsh=ajI0bW41c3lnczBx","https://www.instagram.com/reel/DB3QtFYIZ_d/?igsh=MTVzM2ltYjdteWxpNw==","https://www.instagram.com/reel/C_nRMhZIwDZ/?igsh=b2N3dGZraDNyeXE2"]'::jsonb,
        'https://www.instagram.com/tifanik_bee?igsh=MTAycXJucTlieW9hbQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@tifanik_bee?_t=ZM-8wNn71P9b09&_r=1'
      ),
(
        'Aayooluwa Folasade',
        'aayooluwafolasade',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348022885848',
        'Beauty',
        'Nigeria',
        'active',
        'sadewithlovee@gmail.com',
        'Beauty',
        '["1. https://vm.tiktok.com/ZMSRSAeyW/","2. https://vm.tiktok.com/ZMSRSMwgh/","3. https://vm.tiktok.com/ZMSRSAr9R/"]'::jsonb,
        'https://www.instagram.com/sade.withlove?igsh=MXgyMmh4dG1nZngycg==',
        'https://www.tiktok.com/@sade.withlove?_t=ZM-8wMJnnOcAL9&_r=1'
      ),
(
        'Emomotimi Seibri',
        'emomotimiseibri',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348130350375',
        'Beauty',
        'Nigeria',
        'active',
        'Createwithsesaa@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRSfD9r/","https://vm.tiktok.com/ZMSRSARg4/","https://vm.tiktok.com/ZMSRSaPcx/"]'::jsonb,
        'https://www.instagram.com/officially_sesa/profilecard/?igsh=MThldGN5MTJ3eDRhdQ==',
        'https://www.tiktok.com/@momos_s'
      ),
(
        'Hadassah Onah',
        'hadassahonah',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347085685302',
        'Beauty',
        'Nigeria',
        'active',
        'hadassahonah@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRSMmPR/","https://vm.tiktok.com/ZMSRS52wD/","https://vm.tiktok.com/ZMSRSUftV/"]'::jsonb,
        'https://www.instagram.com/_the.hadassahh?igsh=ZTVxZHBsaWJudmdk&utm_source=qr',
        'https://www.tiktok.com/@_hadassahh?_t=ZM-8wNn36i76n8&_r=1'
      ),
(
        'Isaac blessing',
        'isaacblessing',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348102995485',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'iblessing663@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DIuA_AXM5tQ/?igsh=czNiYnRjM2xmY2J0 https://www.instagram.com/reel/DJWekZVtecM/?igsh=MWEwMjMyeDhpMjZpYg==","https://www.instagram.com/reel/DJqvoBJICqg/?igsh=MTIwMGZnajVkbHNmNg=="]'::jsonb,
        'https://www.instagram.com/isaac_blessing.4?igsh=YWNyZGUyNGdnN3B4',
        'https://vm.tiktok.com/ZMkF97nLk/'
      ),
(
        'Oluwafolafunmi Ogunlashe',
        'oluwafolafunmiogunla',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349090268508',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Oluwafolafunmiogunlashe@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DHYuaaLMdB5/?igsh=aTJuaXk0ZTV4NDJ3","https://www.tiktok.com/@thekiks_/video/7457245305302469894?_r=1&u_code=d429lla8a1d9ml&preview_pb=0&sharer_language=en&_d=eg3gjekd21be2b&share_item_id=7457245305302469894&source=h5_m&timestamp=1747334185&utm_source=copy&tt_from=copy&enable_checksum=1&utm_medium=ios&share_link_id=97F427DE-8395-4229-B52C-2D9745E41882&user_id=6642449165052837894&sec_user_id=MS4wLjABAAAAsjy7CSAyJCqHFiuivNYf2X0hUZZI8OSXCGfjF5ZE4TdjMuzHWH2sKZlMWRPqhJOF&social_share_type=0&ug_btm=b8727","https://vm.tiktok.com/ZMSRSnPhN/"]'::jsonb,
        'https://www.instagram.com/oluwafolafunmiii?igsh=MXNtcXhnYnQyYXFydA%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@thekiks_?_t=ZM-8syvFbpaZNt&_r=1'
      ),
(
        'Komolafe Rebecca Oluwabukunmi',
        'komolaferebeccaoluwa',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349068591755',
        'Fashion',
        'Nigeria',
        'active',
        'bukunmikomolafe04@gmail.com',
        'Fashion',
        '["https://www.instagram.com/reel/DHdrQ6xC6OB/?igsh=eXRpcXpjdnJvZTVw","https://www.instagram.com/reel/DIETUvFiFPM/?igsh=MXA5cmV0aGIzOWQ4dg==","https://www.instagram.com/reel/DJmK9dQiE58/?igsh=MWN0bXU1N3dxeng2Mw=="]'::jsonb,
        'https://www.instagram.com/beekay_the_brand?igsh=MW9sMjg4bWoyZnNrOQ==',
        'https://www.tiktok.com/@beekaythebrand?_t=ZM-8wNo1nbHwIB&_r=1'
      ),
(
        'Blessing Owamokele',
        'blessingowamokele',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349066897778',
        'Beauty',
        'Nigeria',
        'active',
        'Blessingowa.ugc@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRSnuNK/   https://vm.tiktok.com/ZMSRScqGX/","https://vm.tiktok.com/ZMSRSvVVK/"]'::jsonb,
        'https://www.instagram.com/blessing_owa?igsh=MWZjZTMwdXc4M29rMA%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@blessing_owa?_t=ZM-8wNoErdKjmp&_r=1'
      ),
(
        'Fajuyigbe Ewaoluwa',
        'fajuyigbeewaoluwa',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349028378053',
        'Beauty',
        'Nigeria',
        'active',
        'ugcwithjewell@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRAuL7M/","https://vm.tiktok.com/ZMSRAktjH/","https://vm.tiktok.com/ZMSRAu9pm/"]'::jsonb,
        'https://www.instagram.com/jewel._creates?igsh=MWhuczVoencxYjdqdw%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@jewel_creates?_t=ZM-8vAPLAukc7h&_r=1'
      ),
(
        'David Olayimika',
        'davidolayimika',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347065706165',
        'Lifestyle',
        'Nigeria',
        'active',
        'davidolayimika@gmail.com',
        'Lifestyle',
        '["https://www.instagram.com/reel/DGvBw_loDy8/?igsh=MTNlOTJyM3FodzB5bw==","https://www.instagram.com/reel/DJjhcgqoUc6/?igsh=Mm56Zm53bXFtcXox","https://www.instagram.com/reel/DFfmJjsoBPa/?igsh=b2ZnbjFhZTE4dHpt"]'::jsonb,
        'https://www.instagram.com/david_olayimika?igsh=MTVvdHU3YzF6YmI5eg==',
        'https://www.tiktok.com/@davidolayimika?_r=1&_d=ea0a42m0lfadm8&sec_uid=MS4wLjABAAAAwQDz5o0que17aMg1oiRsANPpmaPGGD3j3t7HJPTejK-DvqzjOuhRMHqv4wtq8vsV&share_author_id=6970419859688686598&sharer_language=en&source=h5_m&u_code=dj1ek64j65edhd&timestamp=1747335409&user_id=6970419859688686598&sec_user_id=MS4wLjABAAAAwQDz5o0que17aMg1oiRsANPpmaPGGD3j3t7HJPTejK-DvqzjOuhRMHqv4wtq8vsV&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7501195859829884678&share_link_id=4ca69ef9-4fa9-461a-b407-bfcf91b4db02&share_app_id=1233&ugbiz_name=ACCOUNT&ug_btm=b8727%2Cb7360&social_share_type=5&enable_checksum=1'
      ),
(
        'Naomi Ojeh',
        'naomiojeh',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347010029173',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'naomiojeh21@gmail.com',
        'General/Personal Brand',
        '["https://vt.tiktok.com/ZShxggt1q/","https://vt.tiktok.com/ZShxpRXAW/","https://vt.tiktok.com/ZShxgEkP2/"]'::jsonb,
        'https://www.instagram.com/testiimony__?igsh=YW1wYXhkZXQ0NmYw&utm_source=qr',
        'https://www.tiktok.com/@testiimony__?_t=ZS-8wNqAiS0FT6&_r=1'
      ),
(
        'Oluwafemi',
        'oluwafemi',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348162999753',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'oaoluwafemibinuyo@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRAHBTb/","https://www.instagram.com/reel/DAVLi0ls1P6/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==","https://www.instagram.com/reel/DJMOJZlIVIS/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="]'::jsonb,
        'https://www.instagram.com/thecreativeoluwafemi/profilecard/?igsh=MWtwNnRzaGZwOW5oNw==',
        'https://vm.tiktok.com/ZMSRAHBTb/'
      ),
(
        'Kaosara Jimoh',
        'kaosarajimoh',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348105611010',
        'Beauty',
        'Nigeria',
        'active',
        'jimohkaosaraopeyemi@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/@tharaalli/video/7502757225308425478?_r=1","https://vm.tiktok.com/ZMSRAGeDG/","https://vm.tiktok.com/ZMSRDYVWk/"]'::jsonb,
        'https://www.instagram.com/thara__xx/profilecard/?igsh=YTBqZWN2bzRuazl3',
        'https://www.tiktok.com/@tharaalli?_t=8s2WzDlI3jK&_r=1'
      ),
(
        'Nwanozie Chiamaka tessy',
        'nwanoziechiamakatess',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349152632097',
        'Beauty',
        'Nigeria',
        'active',
        'chiamakanwanozie09@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRD62d9/   https://vm.tiktok.com/ZMSRD6VW7/     https://www.instagram.com/reel/DJB_xPKIBpb/?igsh=MXRyenNpY2Z0bnR6bw=="]'::jsonb,
        'https://www.instagram.com/tessyexplorer/profilecard/?igsh=MTl6ZG9hN3ZseHN2aw==',
        'https://vm.tiktok.com/ZMSRD2sk2/'
      ),
(
        'Emokpae Remilekun',
        'emokpaeremilekun',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349013255068',
        'Beauty',
        'Nigeria',
        'active',
        'remilekunemokpae@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRyd42Q/","https://vm.tiktok.com/ZMSRy6KGP/","https://vm.tiktok.com/ZMSRUEd9v/"]'::jsonb,
        'https://www.instagram.com/remil.ekun?igsh=cG5saXBsMXQweGlv&utm_source=qr',
        'https://www.tiktok.com/@_remilekun_?_t=ZM-8wNvfeA362f&_r=1'
      ),
(
        'Lydia Olajide',
        'lydiaolajide',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347040276113',
        'Beauty',
        'Nigeria',
        'active',
        'lydiajess7@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/t/ZP864BNGR/","https://www.tiktok.com/t/ZP86XwUwa/","https://www.tiktok.com/t/ZP86XoVBV/"]'::jsonb,
        'https://www.instagram.com/lydia_jess7?igsh=MXgwczJjd2Jxam5rcQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@lydiajess7?_t=ZP-8wNvdliH9tG&_r=1'
      ),
(
        'Jesutoni Akoni',
        'jesutoniakoni',
        'Content creator specializing in Finance. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348134817431',
        'Finance',
        'Nigeria',
        'active',
        'ugcbyjesutoni@gmail.com',
        'Finance',
        '[]'::jsonb,
        'https://www.instagram.com/ugcbyjesutoni',
        'https://www.tiktok.com/@ugcbyjesutoni_'
      ),
(
        'Uzoamaka Christiana Obasi',
        'uzoamakachristianaob',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347036305438',
        'General/Personal Brand',
        'Nigeria',
        'active',
        '@amy.no1sound@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DIt30Klt02A/?igsh=MTk5dXBwMjlvbjVybw==","https://www.instagram.com/reel/DImHIMLtZPK/?igsh=MTg1amEyY3luMHRheQ==","https://www.instagram.com/reel/DImHIMLtZPK/?igsh=MTg1amEyY3luMHRheQ=="]'::jsonb,
        'https://www.instagram.com/amytianagloball?igsh=ZXFyOXRobDRheDNr&utm_source=qr',
        'I just lost my old account at 25k followers'
      ),
(
        'Oghenekeno Ikime',
        'oghenekenoikime',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348136142346',
        'Beauty',
        'Nigeria',
        'active',
        'contactkenogha@gmail.com',
        'Beauty',
        '["https://vt.tiktok.com/ZShxtpKpv/","https://vt.tiktok.com/ZShxtg8uK/","https://vt.tiktok.com/ZShxtCEEd/"]'::jsonb,
        'https://www.instagram.com/kenogha?igsh=MTBxc3hpbTBydWxyMw%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@kenogha?_t=ZS-8wNwlHcgmpz&_r=1'
      ),
(
        'Philip Fab-Uche',
        'philipfabuche',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347054296947',
        'Lifestyle',
        'Nigeria',
        'active',
        'philipfabuche@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMSRy5WLe/","https://vm.tiktok.com/ZMSRykq2w/","https://vm.tiktok.com/ZMSRyCY6S/"]'::jsonb,
        'https://www.instagram.com/philipfabuche?igsh=MTE2OHcwM2hua3k5YQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@philipfabuche?_t=ZM-8wNwt6uXPYV&_r=1'
      ),
(
        'Mary Jeje',
        'maryjeje',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348138586339',
        'Beauty',
        'Nigeria',
        'active',
        'jejemary54@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRyDKuW/  https://vm.tiktok.com/ZMSRyaKxy/","https://vm.tiktok.com/ZMSRyukqT/"]'::jsonb,
        'https://www.instagram.com/_melaninmary_?igsh=MXIzemxyMnh1bmlteA%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@_melaninmary_?_t=ZM-8wNxFMqcUjN&_r=1'
      ),
(
        'Ekereuwem Dorothea',
        'ekereuwemdorothea',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349017492703',
        'Beauty',
        'Nigeria',
        'active',
        'ekereuwemdorothea@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DGNUI-Gopa5/?igsh=MXMxbWFramp3MGlhYQ==","https://www.instagram.com/reel/DGFgHl7IWiK/?igsh=ZG1ndHJiZzlibTU0","https://www.instagram.com/reel/DI0mSjhIhze/?igsh=YnRoNGNkNzcyNDh2"]'::jsonb,
        'https://www.instagram.com/_.dorombaby?igsh=MTVwdGJ3c2tsZGtxdQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@theadietss?_t=ZM-8wNx8c3SRIk&_r=1'
      ),
(
        'Ugwu Chioma Divinegift',
        'ugwuchiomadivinegift',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347034904318',
        'Lifestyle',
        'Nigeria',
        'active',
        'chiomaugwu070@gmail.com',
        'Lifestyle',
        '["1. https://vm.tiktok.com/ZMSRyhQPp/","2. https://vm.tiktok.com/ZMSRygRRF/","3. https://vm.tiktok.com/ZMSRyqsk4/"]'::jsonb,
        'https://www.instagram.com/chioma_ddivine?igsh=ODdpeGhicHo1b3c4&utm_source=qr',
        'https://www.tiktok.com/@chioma.ugwu95?_t=ZM-8wNxIUvhKgH&_r=1'
      ),
(
        'Oyugbo Eboselumhen',
        'oyugboeboselumhen',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347030790319',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'lulu.oyugbo@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRyksHY/","https://vm.tiktok.com/ZMSRy4Rft/","https://vm.tiktok.com/ZMSRyCmVs/"]'::jsonb,
        'https://www.instagram.com/antifairyyy/profilecard/?igsh=MXIxank4a2YycDE3Yw==',
        'https://www.tiktok.com/@maybeantifairy?_t=ZM-8wNxPMAEj4g&_r=1'
      ),
(
        'Melanie Emeka',
        'melanieemeka',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349028963364',
        'Lifestyle',
        'Nigeria',
        'active',
        'melanieeemeka@gmail.com',
        'Lifestyle',
        '["https://www.instagram.com/reel/DD5CoXDtZyR/?igsh=MWR5NmtkZzFwdGNzbw== https://www.instagram.com/reel/DG_QA60NUqF/?igsh=Z2N3bmExYXhlMzJn","https://www.instagram.com/reel/DIb69_ONogf/?igsh=MXV0NHBzbGI5N2wzNQ=="]'::jsonb,
        'https://www.instagram.com/simply.melaniee_?igsh=OGRoN3AxOG1tcnhn&utm_source=qr',
        'https://www.tiktok.com/@simply.melaniee?_t=ZM-8wNxWxfN10x&_r=1'
      ),
(
        'Omoregbe Helen Osaseye',
        'omoregbehelenosaseye',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347068768636',
        'Beauty',
        'Nigeria',
        'active',
        'omosellen@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/C4Lf0lQqqb7/?igsh=MXV0cXpudzcwMnZiNQ==","https://www.instagram.com/reel/C4vCRr5KByi/?igsh=MTBueHFtN2d1OGRnaw==","https://www.instagram.com/reel/DFvSzyMInut/?igsh=MTF2dGZpdTBkZGN0Zg=="]'::jsonb,
        'https://www.instagram.com/osas_ellen?igsh=b3JqcXRsZDd0MXBp&utm_source=qr',
        'https://www.tiktok.com/@ellen_osas?_t=ZM-8wNxkfr6tcd&_r=1'
      ),
(
        'Jinadu Zainab',
        'jinaduzainab',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349018471298',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'jinaduzainab91@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRy3k1h/","https://vm.tiktok.com/ZMSRyvag9/","https://vm.tiktok.com/ZMSRf1wbD/"]'::jsonb,
        'https://www.instagram.com/zeelikespetals?igsh=MTUwOWxidzdncnBxcg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@justz.e.e?_t=ZM-8wNy0vyv04r&_r=1'
      ),
(
        'Folatomi Ogidan',
        'folatomiogidan',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348029595567',
        'Beauty',
        'Nigeria',
        'active',
        'ogidanfolatomi@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/@queenoflasgidi_/video/7503588484704144646?_r=1&u_code=e548g0amj9jd4e&preview_pb=0&sharer_language=en&_d=edkglja2h5jm0l&share_item_id=7503588484704144646&source=h5_m&timestamp=1747342889&ug_btm=b8727","https://www.tiktok.com/@queenoflasgidi_/video/7496806933161053446?_r=1&u_code=e548g0amj9jd4e&preview_pb=0&sharer_language=en&_d=edkglja2h5jm0l&share_item_id=7496806933161053446&source=h5_m&timestamp=1747343023&ug_btm=b8727","https://www.tiktok.com/@queenoflasgidi_/video/7493492906578201861?_r=1&u_code=e548g0amj9jd4e&preview_pb=0&sharer_language=en&_d=edkglja2h5jm0l&share_item_id=7493492906578201861&source=h5_m&timestamp=1747343121&ug_btm=b8727"]'::jsonb,
        'https://www.instagram.com/queenoflasgidi1_',
        'https://www.tiktok.com/@queenoflasgidi_?_r=1&_d=edkglja2h5jm0l&sec_uid=MS4wLjABAAAAjGf1FSP90QMC3afgtlQPXv7RbygqJfgp4j5T48J7dR2ptzPKwThaMxmBZQqaoGHs&share_author_id=7170253696264684545&sharer_language=en&source=h5_m&u_code=e548g0amj9jd4e&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAjGf1FSP90QMC3afgtlQPXv7RbygqJfgp4j5T48J7dR2ptzPKwThaMxmBZQqaoGHs&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7170253696264684545&share_link_id=71289269-5E75-4DF7-AD65-F33ED8056AFD&share_app_id=1233'
      ),
(
        'Wisdom Aghe',
        'wisdomaghe',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348035855417',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'wisdomaghe@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRfXT44/","https://vm.tiktok.com/ZMSRfrNK3/","https://www.instagram.com/reel/DId2R5DKXsa/?igsh=MTluOW4zdW85Zzlqaw=="]'::jsonb,
        'https://www.instagram.com/wiseage06?igsh=eWY3bG9zdGJ0eTQ4',
        'https://www.tiktok.com/@wisege06?_t=ZM-8wO05tqyMOU&_r=1'
      ),
(
        'Tuntamilore Tawak',
        'tuntamiloretawak',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348097303020',
        'Fashion',
        'Nigeria',
        'active',
        'ttawaq@gmail.com',
        'Fashion',
        '["tiktok.com/@tuntamilore"]'::jsonb,
        'instagram.com/tuntamilore',
        'tiktok.com/tuntamilore'
      ),
(
        'Nicole Madubu Dauda',
        'nicolemadubudauda',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349138346030',
        'Fashion',
        'Nigeria',
        'active',
        'daudajanada2@gmail.com',
        'Fashion',
        '["https://vm.tiktok.com/ZMSRPveuS/","https://vm.tiktok.com/ZMSRPTvsq/","https://vm.tiktok.com/ZMSRPqH9h/"]'::jsonb,
        'https://www.instagram.com/nicol3_dauda?igsh=MWY5NTcxNjI1cmM1Yw%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@janad3_?_t=ZM-8wO39bVtK9l&_r=1'
      ),
(
        'Emmanuella Meansworth',
        'emmanuellameansworth',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348153727999',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'bookingnuella@gmail.com',
        'General/Personal Brand',
        '["https://www.instagram.com/reel/DJlsHviNkoC/?igsh=d2pmbW5qMWtkbXly","https://www.instagram.com/reel/DIMxQA3tnyV/?igsh=a3hwc3RjZDFmdjVt","https://vm.tiktok.com/ZMSRa8Qjy/"]'::jsonb,
        'https://www.instagram.com/nuellameansworth?igsh=MTgybmFxM3kydDN3&utm_source=qr',
        'www.tiktok.com/@nuellameansworth'
      ),
(
        'Owa Bolatito Fortune',
        'owabolatitofortune',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348163536533',
        'Lifestyle',
        'Nigeria',
        'active',
        'owafortune@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMSRuc8QS/","https://vm.tiktok.com/ZMSRu3RxA/","https://vm.tiktok.com/ZMSRuTrGW/"]'::jsonb,
        'https://www.instagram.com/_titoverse?igsh=YzlneTlpdGhtZWpx',
        'https://www.tiktok.com/@_titoverse?_t=ZM-8wOCp1zl2oR&_r=1'
      ),
(
        'Mitchelle Ogu',
        'mitchelleogu',
        'Content creator specializing in Health & Wellness. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348101378828',
        'Health & Wellness',
        'Nigeria',
        'active',
        'Mitchelleogu@gmail.com',
        'Health & Wellness',
        '["https://vm.tiktok.com/ZMSRCAT5m/","https://vm.tiktok.com/ZMSRCg4D8/","https://www.instagram.com/reel/DCPP0dqoT-G/?igsh=amQxOGd5bXMwM3U0"]'::jsonb,
        'https://www.instagram.com/mitch_elleeeeee?igsh=MXMzOWM2aGhuZXU3bQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@mitch_elleeeeee?_t=ZM-8wONSly346v&_r=1'
      ),
(
        'Princess Jewel Jel-Edema',
        'princessjeweljeledem',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349061312216',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'princessjewel80@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRV1qHH/","https://vm.tiktok.com/ZMSRVeWjb/","https://vm.tiktok.com/ZMSRVebg5/"]'::jsonb,
        'https://www.instagram.com/thatebonychic?igsh=MXJ0aWFoN3B6bmlsaQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@thatebonychic?_t=ZM-8wOWeUC9qMf&_r=1'
      ),
(
        'Praise Boldwill',
        'praiseboldwill',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+23422968979205',
        'Beauty',
        'Nigeria',
        'active',
        'ugcwithnenye@gmail.com',
        'Beauty',
        '[]'::jsonb,
        'https://instagram.com/ugcwithnenye',
        'https://tiktok.com/@ugcwithnenye'
      ),
(
        'Khaerat Alaran',
        'khaeratalaran',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347033588613',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Khaeratalaran@gmail.com',
        'General/Personal Brand',
        '[]'::jsonb,
        'https://www.instagram.com/through_ades_lens?igsh=ODM3YmNpaHI3azMx&utm_source=qr',
        'https://www.tiktok.com/@through.ades.lens?_t=ZM-8wJlh36qaik&_r=1'
      ),
(
        'Boluwatife mary',
        'boluwatifemary',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349064420471',
        'Beauty',
        'Nigeria',
        'active',
        'Boluwatifeogundola77@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRVvETJ/"]'::jsonb,
        'https://www.instagram.com/bibi_brown01/profilecard/?igsh=ZDNjaWw4dHU4bnFx',
        'https://www.tiktok.com/@boluwatife_thecreator?_t=ZM-8wOalQAdhF1&_r=1'
      ),
(
        'Amarachi Ejike',
        'amarachiejike',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348103345394',
        'Beauty',
        'Nigeria',
        'active',
        'amarachiejike200@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DJD4G8Ws7Pl/?igsh=MW91OXBndjl2OWR0MQ==","https://www.instagram.com/reel/DIlcJigsvDe/?igsh=MWxteDlpcnB6ZTgzaQ==","https://www.instagram.com/reel/DJHg2JMMMuk/?igsh=MWVhY2JsYXJ4YjF0NQ=="]'::jsonb,
        'https://www.instagram.com/amaraplush_1?igsh=MWwyOXZsYTNkNzFn&utm_source=qr',
        'https://www.tiktok.com/@amaraplush?_t=ZM-8wOcaz12OEJ&_r=1'
      ),
(
        'Obi Chioma',
        'obichioma',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349131069349',
        'Lifestyle',
        'Nigeria',
        'active',
        'ugcoma@gmail.com',
        'Lifestyle',
        '[]'::jsonb,
        'https://www.instagram.com/oma.ugc?igsh=MTdtMmpwbjBycnY5dA%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@oma_ugc?_t=8mPUdKvDdCQ&_r=1'
      ),
(
        'Muyinat Yusuf',
        'muyinatyusuf',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347047631461',
        'Beauty',
        'Nigeria',
        'active',
        'muyinatyusuf8@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DImDR3hMMHR/?igsh=MTViaTE4dzBxdHh3ZA==","https://vm.tiktok.com/ZMSRqXsx6/","https://vm.tiktok.com/ZMSRqWJSX/"]'::jsonb,
        'https://www.instagram.com/_folaaaaaa/profilecard/?igsh=NmlqYXgwMDAxdzl3',
        'https://www.tiktok.com/@folaaaaaaa?_t=ZM-8ujZvZZKWaF&_r=1'
      ),
(
        'Folatomi Ogidan',
        'folatomiogidan1',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348029595567',
        'Beauty',
        'Nigeria',
        'active',
        'ogidanfolatomi@gmail.com',
        'Beauty',
        '["https://www.tiktok.com/@queenoflasgidi_/video/7503588484704144646?_r=1&u_code=e548g0amj9jd4e&preview_pb=0&sharer_language=en&_d=edkglja2h5jm0l&share_item_id=7503588484704144646&source=h5_m&timestamp=1747342889&ug_btm=b8727","https://www.tiktok.com/@queenoflasgidi_/video/7496806933161053446?_r=1&u_code=e548g0amj9jd4e&preview_pb=0&sharer_language=en&_d=edkglja2h5jm0l&share_item_id=7496806933161053446&source=h5_m&timestamp=1747343023&ug_btm=b8727","https://www.tiktok.com/@queenoflasgidi_/video/7493492906578201861?_r=1&u_code=e548g0amj9jd4e&preview_pb=0&sharer_language=en&_d=edkglja2h5jm0l&share_item_id=7493492906578201861&source=h5_m&timestamp=1747343121&ug_btm=b8727"]'::jsonb,
        'https://www.instagram.com/queenoflasgidi1_',
        'https://www.tiktok.com/@queenoflasgidi_?_r=1&_d=edkglja2h5jm0l&sec_uid=MS4wLjABAAAAjGf1FSP90QMC3afgtlQPXv7RbygqJfgp4j5T48J7dR2ptzPKwThaMxmBZQqaoGHs&share_author_id=7170253696264684545&sharer_language=en&source=h5_m&u_code=e548g0amj9jd4e&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAjGf1FSP90QMC3afgtlQPXv7RbygqJfgp4j5T48J7dR2ptzPKwThaMxmBZQqaoGHs&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7170253696264684545&share_link_id=71289269-5E75-4DF7-AD65-F33ED8056AFD&share_app_id=1233'
      ),
(
        'Vivian Aniekwe',
        'viviananiekwe',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349050970145',
        'Beauty',
        'Nigeria',
        'active',
        'aniekwevivian70@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRbRtCE/","https://www.tiktok.com/@_veetheugcreator_/video/7498826450477272375?_r=1&u_code=e3cfbijjc1hf0c&preview_pb=0&sharer_language=en&_d=eae2m9336e17he&share_item_id=7498826450477272375&source=h5_m&timestamp=1747380466&user_id=7134329345028883462&sec_user_id=MS4wLjABAAAAj2cD9LA1gQ3T5kisfvBXDsc1Ee8jMQmSsz6chziYXPJot5jjx7Eo7ZDWyLFOR6nw&social_share_type=0&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7469157090545174277&share_link_id=6eca482b-e5eb-4739-b61f-afb71c7f1f70&share_app_id=1233&ugbiz_name=MAIN&ug_btm=b8727%2Cb2878&link_reflow_popup_iteration_sharer=%7B%22click_empty_to_play%22%3A1%2C%22dynamic_cover%22%3A1%2C%22follow_to_play_duration%22%3A-1.0%2C%22profile_clickable%22%3A1%7D&enable_checksum=1","https://www.tiktok.com/@_veetheugcreator_/video/7496970513974086917?_r=1&u_code=e3cfbijjc1hf0c&preview_pb=0&sharer_language=en&_d=eae2m9336e17he&share_item_id=7496970513974086917&source=h5_m&timestamp=1747380502&user_id=7134329345028883462&sec_user_id=MS4wLjABAAAAj2cD9LA1gQ3T5kisfvBXDsc1Ee8jMQmSsz6chziYXPJot5jjx7Eo7ZDWyLFOR6nw&social_share_type=0&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7469157090545174277&share_link_id=34fb81cf-86fa-4777-9c5b-b3fdbb734f27&share_app_id=1233&ugbiz_name=MAIN&ug_btm=b8727%2Cb2878&link_reflow_popup_iteration_sharer=%7B%22click_empty_to_play%22%3A1%2C%22dynamic_cover%22%3A1%2C%22follow_to_play_duration%22%3A-1.0%2C%22profile_clickable%22%3A1%7D&enable_checksum=1"]'::jsonb,
        'https://www.instagram.com/_veetheugcreator_?igsh=dHdsc252bXJrbzlw',
        'https://www.tiktok.com/@_veetheugcreator_?_t=ZM-8sur61w1BtG&_r=1'
      ),
(
        'Sonia Ibeh',
        'soniaibeh',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348108897411',
        'Beauty',
        'Nigeria',
        'active',
        'ibehsonia27@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRbVvwX/","https://vm.tiktok.com/ZMSRbD9F1/","https://vm.tiktok.com/ZMSRbubp1/"]'::jsonb,
        'https://www.instagram.com/creator.ibehsonia?igsh=MXhuOHVybXhyMGQzZA==',
        'https://www.tiktok.com/@creator_ibehsonia'
      ),
(
        'Serena Arueya',
        'serenaarueya',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349113018463',
        'Beauty',
        'Nigeria',
        'active',
        'serenareya06@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DIeeQgsKu1u/?igsh=MWg0NjVycDhmOHpzdg==","https://www.instagram.com/reel/DJT3QtmqDC9/?igsh=a25wcnA3NWRpM3hv","https://www.instagram.com/reel/DFDDemkMhut/?igsh=MWM3MGdwNGpieWFldA=="]'::jsonb,
        'https://www.instagram.com/caramel.reya?igsh=MWh5aWJoa2E4bm1tYQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@k.editsssx?_t=ZM-8vos1SFjKEA&_r=1'
      ),
(
        'Doreen Nwankwo',
        'doreennwankwo',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347033341296',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Amadoreen02@gmail.con',
        'General/Personal Brand',
        '["1. https://www.instagram.com/reel/Co7v__aIMt1","2. https://www.instagram.com/reel/DG7hbbxIhoD"]'::jsonb,
        'https://www.instagram.com/ama.doreenn',
        'https://www.tiktok.com/@ama_doreenn'
      ),
(
        'Efua Divine',
        'efuadivine',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349078655695',
        'Beauty',
        'Nigeria',
        'active',
        'bizwithefua37@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMSRgJQDg/","https://vm.tiktok.com/ZMSRbtS3E/","https://vm.tiktok.com/ZMSRgdNGP/"]'::jsonb,
        'https://www.instagram.com/ugcwithefua',
        'https://www.tiktok.com/@ugcwithefua'
      ),
(
        'Aruleba oluwatoyin',
        'arulebaoluwatoyin',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348036646184',
        'Lifestyle',
        'Nigeria',
        'active',
        'Oluwatoyinaruleba@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMSRg9fEW/","https://vm.tiktok.com/ZMSRgD5oa/"]'::jsonb,
        'https://www.instagram.com/_toyiiin?igsh=c2k4N2JzcWJkZDFj&utm_source=qr',
        'https://www.tiktok.com/@_toyiiin?_t=ZM-8wOoHeiBvi3&_r=1'
      ),
(
        'Mercy Stephanie madu',
        'mercystephaniemadu',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349065029920',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'Mercystephainemadu.ms@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSRsTqkw/","https://vm.tiktok.com/ZMSRs9B3V/","https://vm.tiktok.com/ZMSRs9ExL/"]'::jsonb,
        'https://www.instagram.com/irishmirage?igsh=enhpMGxlZWFydXU4&utm_source=qr',
        'www.tiktok.com/@obimduke'
      ),
(
        'Eunice Chiamaka Maduak',
        'eunicechiamakamaduak',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348160251246',
        'Beauty',
        'Nigeria',
        'active',
        'Aimieeemaduka@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DJcft2OIWSx/?igsh=MXUyazlvbnA1Z2Fi"]'::jsonb,
        'https://www.instagram.com/aimieeemaduka',
        'https://www.tiktok.com/@aimieeemaduka?_t=ZM-8vOz8p1w56T&_r=1'
      ),
(
        'Uzoamaka C. Anyaegbuna',
        'uzoamakacanyaegbuna',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349137727544',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'uzooca@gmail.com',
        'General/Personal Brand',
        '["https://www.tiktok.com/t/ZP86qNJm5/","https://www.tiktok.com/t/ZP86VWcyV/","https://www.tiktok.com/t/ZP86qLCJo/"]'::jsonb,
        'https://www.instagram.com/uzoca',
        'https://www.tiktok.com/@uzoca?_t=ZP-8wPBxJ9tL4Q&_r=1'
      ),
(
        'Mira oge',
        'miraoge',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347045028971',
        'Beauty',
        'Nigeria',
        'active',
        'Miraugc04@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZNdrSc5nV/","https://vm.tiktok.com/ZNdrStqy8/","https://vm.tiktok.com/ZNdrSGKVt/"]'::jsonb,
        'https://www.instagram.com/ugc.with.mira?igsh=azNqMmZicnJoOHUz',
        'https://www.tiktok.com/@ugc.with.mira?_t=ZN-8w4aUIjHeze&_r=1'
      ),
(
        'Geniva',
        'geniva',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349156738756',
        'Beauty',
        'Nigeria',
        'active',
        'genivacollabs@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMS8LjTMC/","https://vm.tiktok.com/ZMS8LRcqV/","https://vm.tiktok.com/ZMS88t27j/"]'::jsonb,
        'https://www.instagram.com/_geniva?igsh=MTEzcWs2bjNnbWtsZA==',
        'https://www.tiktok.com/@vibewithiva_?_t=ZM-8wPkZaqUjvb&_r=1'
      ),
(
        'Damilola Okegbemi',
        'damilolaokegbemi',
        'Content creator specializing in Travel. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348160787914',
        'Travel',
        'Nigeria',
        'active',
        'Damiexplores@gmail.com',
        'Travel',
        '["https://www.instagram.com/reel/DHRJzSeMe-F/?igsh=OXNxcHY2Y2N5czVo","https://www.instagram.com/reel/DJmBbUPCrXB/?igsh=MTZ5ZDJ5a2dvcnZocA==","https://vm.tiktok.com/ZMS8Lqu4q/"]'::jsonb,
        'https://www.instagram.com/damiexplores?igsh=azZzZWtkeHFzMm5z',
        'https://www.tiktok.com/@damiexplores?_t=ZM-8wPkYy57E73&_r=1'
      ),
(
        'Geniva',
        'geniva1',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349156738756',
        'Beauty',
        'Nigeria',
        'active',
        'genivacollabs@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMS8LjTMC/","https://vm.tiktok.com/ZMS8LRcqV/","https://vm.tiktok.com/ZMS88t27j/"]'::jsonb,
        'https://www.instagram.com/_geniva?igsh=MTEzcWs2bjNnbWtsZA==',
        'https://www.tiktok.com/@vibewithiva_?_t=ZM-8wPkZaqUjvb&_r=1'
      ),
(
        'Gabson Chidubem Mary-Immaculata',
        'gabsonchidubemmaryim',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2347019762259',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'theladybirdng@gmail.com',
        'General/Personal Brand',
        '[]'::jsonb,
        'https://www.instagram.com/_theladybird_/profilecard/?igsh=MTlpajBjaTZxamhvMA==  Here',
        'https://www.tiktok.com/@_theladybird_?_t=ZM-8wQO0gTbqz8&_r=1'
      ),
(
        'Okunade Titilade Abiodun',
        'okunadetitiladeabiod',
        'Content creator specializing in Lifestyle. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349135720577',
        'Lifestyle',
        'Nigeria',
        'active',
        'ladeokunade8@gmail.com',
        'Lifestyle',
        '["https://vm.tiktok.com/ZMS8KcyL4/","https://vm.tiktok.com/ZMS8KWDNA/","https://vm.tiktok.com/ZMS8KKB3U/"]'::jsonb,
        'https://www.instagram.com/pyt.lade?igsh=anJyb250bnoxaHE4&utm_source=qr',
        'https://www.tiktok.com/@ladee.ok?_t=ZM-8wRxQbFB7va&_r=1'
      ),
(
        'Geniva',
        'geniva2',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349156738756',
        'Beauty',
        'Nigeria',
        'active',
        'genivacollabs@gmail.com',
        'Beauty',
        '["https://vm.tiktok.com/ZMS8LjTMC/","https://vm.tiktok.com/ZMS8LRcqV/","https://vm.tiktok.com/ZMS88t27j/"]'::jsonb,
        'https://www.instagram.com/_geniva?igsh=MTEzcWs2bjNnbWtsZA==',
        'https://www.tiktok.com/@vibewithiva_?_t=ZM-8wPkZaqUjvb&_r=1'
      ),
(
        'Lajide Esther',
        'lajideesther',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348102735046',
        'Beauty',
        'Nigeria',
        'active',
        'estherlajide@iCloud.com',
        'Beauty',
        '["https://www.instagram.com/reel/DIJnIbGIMGk/?igsh=NWVpZWNtOWZjdTY3","https://www.instagram.com/reel/DH86kygohOD/?igsh=cjN1cHZrMzVhdDlk","https://www.instagram.com/reel/DFxpw5SISFq/?igsh=eHZycmdpYjBwZHpy"]'::jsonb,
        'https://www.instagram.com/estherlajide?igsh=Zm5sNHJhM3c0a25z&utm_source=qr',
        'https://www.tiktok.com/@estherlajide?_t=ZM-8wWBKRC0az2&_r=1'
      ),
(
        'Eseoghene Asagba',
        'eseogheneasagba',
        'Content creator specializing in Health & Wellness. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349052648580',
        'Health & Wellness',
        'Nigeria',
        'active',
        'esethenutritionist@gmail.com',
        'Health & Wellness',
        '["https://www.instagram.com/reel/DIhbrOwoDwR/?igsh=NzNzYzNyMzllbzZi","https://www.instagram.com/reel/DE9vHEDI98s/?igsh=MWEzcDM5MWRlbDA4cw==","https://www.instagram.com/reel/DJfAcncoqN8/?igsh=ZWR5NGU4Y3VkbzVo"]'::jsonb,
        'https://www.instagram.com/esethenutritionist_?igsh=azVqbDU3dDQxZmlm&utm_source=qr',
        'https://www.tiktok.com/@ese.a.a?_t=ZN-8wypyRtTCHW&_r=1'
      ),
(
        'Adebayo Adeola Oluwatomisin',
        'adebayoadeolaoluwato',
        'Content creator specializing in Beauty. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349136713788',
        'Beauty',
        'Nigeria',
        'active',
        'Hertomisincreativeco1@gmail.com',
        'Beauty',
        '["https://www.instagram.com/reel/DHS3ZdUsF5b/?igsh=MThiY3FvOXBwYThubQ==","https://www.instagram.com/reel/DHDMZtRukih/?igsh=MTF0b2o0anJxNXN5ag==","https://www.instagram.com/reel/DGvhTy3Ky6a/?igsh=emV6MzBycjh4YjZq"]'::jsonb,
        'https://www.instagram.com/her_tomisin?igsh=MTVuemcxNGZ6amh2eQ%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@hertomiisin?_t=ZM-8wyu6R8qihU&_r=1'
      ),
(
        'Onwukwe Marykate Chizoba',
        'onwukwemarykatechizo',
        'Content creator specializing in Fashion. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2349060372607',
        'Fashion',
        'Nigeria',
        'active',
        'Onwukwemarykate@gmail.com',
        'Fashion',
        '["https://www.instagram.com/reel/CugjgjioFM9/?igsh=MWc0MXl4ZWhpZmQyag==","https://www.instagram.com/reel/DKh6Vd9tZDU/?igsh=MXVua3VvY3JidGtiOQ==","https://www.instagram.com/reel/DJ3xhAsNFFk/?igsh=MTZtcjYwaGc5Y2I1Nw=="]'::jsonb,
        'https://www.instagram.com/the_curve_girl_?igsh=cjY0ZnJ3aThiemtr&utm_source=qr',
        'https://www.tiktok.com/@modelkatrine?_t=ZM-8wyw2j0Chr3&_r=1'
      ),
(
        'Mayowa Fagbure',
        'mayowafagbure',
        'Content creator specializing in Technology. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348079240807',
        'Technology',
        'Nigeria',
        'active',
        'Mayowafagburedigital@gmail.com',
        'Tech',
        '["https://www.instagram.com/reel/DJb-Z9xMJdJ/?igsh=ZXc3bWV6cDFubWU2","https://www.instagram.com/reel/DI30MZsMmKR/?igsh=MXV6dG1kcGkwcWd4cg==","https://www.instagram.com/reel/DJpLJYtMZY-/?igsh=cDUzcjVuMzhmcQ=="]'::jsonb,
        'https://www.instagram.com/mayowafagbure?igsh=MWZobWtma2FycGszMw%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@mayowafagbure?_t=ZN-8wyxl6nXT8h&_r=1'
      ),
(
        'Peace Oluwasanmi',
        'peaceoluwasanmi',
        'Content creator specializing in General/Personal Brand. Available for collaborations!',
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
        '+2348108034041',
        'General/Personal Brand',
        'Nigeria',
        'active',
        'oluwasanmipeace@gmail.com',
        'General/Personal Brand',
        '["https://vm.tiktok.com/ZMSSMqJgx/","https://vm.tiktok.com/ZMSSr1QQt/"]'::jsonb,
        'https://www.instagram.com/shalom.meanspeace?igsh=MWlqNWhwZnpyZnpsYg%3D%3D&utm_source=qr',
        'https://www.tiktok.com/@shalommeanspeace_?_t=ZM-8wz0BVhD0is&_r=1'
      );