-- Insert creators from CSV import
INSERT INTO creators (
    name, 
    username, 
    email, 
    whatsapp_number, 
    industry, 
    category, 
    video_portfolio, 
    instagram_profile, 
    tiktok_profile, 
    bio, 
    status, 
    location
) VALUES 
(
    'Afolarin Wuraola',
    'afolarinwuraola',
    'afolarinwuraola@gmail.com',
    '+2348081795588',
    'Lifestyle',
    'Lifestyle',
    '["https://vm.tiktok.com/ZMSRFw6hJ/ https://vm.tiktok.com/ZMSRFqwtE/  https://vm.tiktok.com/ZMSRFo26Q/"]'::jsonb,
    'https://www.instagram.com/wuraaaah?igsh=MTlkcWxwYm84aDF4dg%3D%3D&utm_source=qr',
    'https://www.tiktok.com/@wuraaagold?_t=ZM-8wNOjWzAodz&_r=1',
    'Content creator specializing in Lifestyle. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Amiso Lucky Ibitamuno',
    'amisoluckyibitamuno',
    'luckyamiso15@gmail.com',
    '+2349057695019',
    'General/Personal Brand',
    'General/Personal Brand',
    '["https://www.tiktok.com/@a.agencyofficial/video/7461329221151984901?is_from_webapp=1&sender_device=pc&web_id=7501613679088010757. https://www.instagram.com/reel/C6TyzW1o7IC/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==   https://www.instagram.com/reel/C_lWdwMI_L-/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="]'::jsonb,
    'https://www.instagram.com/_luckyai?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    'https://www.tiktok.com/@_luckyai?is_from_webapp=1&sender_device=pc',
    'Content creator specializing in General/Personal Brand. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Akinyinka Mololuwa',
    'akinyinkamololuwa',
    'jamesakinyinka@gmail.com',
    '+2349139151744',
    'General/Personal Brand',
    'General/Personal Brand',
    '["https://vm.tiktok.com/ZMSRrc5Rs/"]'::jsonb,
    'https://www.instagram.com/directorcruizeee/profilecard/?igsh=MTBlaHBrZG9qbDg2bw==',
    'https://www.tiktok.com/@directorcruizeee?_t=ZM-8wNeBB6P4rd&_r=1',
    'Content creator specializing in General/Personal Brand. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Chimdinma Udeze',
    'chimdinmaudeze',
    'Ugcwithdrchim@gmail.com',
    '+2348137834526',
    'Health & Wellness',
    'Health & Wellness',
    '[]'::jsonb,
    'https://www.instagram.com/lifewith_drchim/profilecard/?igsh=YjJhcTB6ZmM4dHd5',
    'https://www.tiktok.com/@ugcwithdrchim_?_t=8mBiCdAaFHB&_r=1',
    'Content creator specializing in Health & Wellness. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Confidence CHIKAMSO',
    'confidencechikamso',
    'Kamsobrandcollab@gmail.com',
    '+2348149076477',
    'Beauty',
    'Beauty',
    '["https://www.tiktok.com/@kamso_ugc_creator/video/7502389897114799365?_r=1&u_code=edhj0bf59c94ej&preview_pb=0&sharer_language=en&_d=ec4aabki0e9666&share_item_id=7502389897114799365&source=h5_m&timestamp=1747331495&utm_source=copy&tt_from=copy&enable_checksum=1&utm_medium=ios&share_link_id=B48CFA68-895F-452C-9661-29F2F09DA18F&user_id=7358384967619200005&sec_user_id=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&social_share_type=0&ug_btm=b8727"]'::jsonb,
    'https://www.tiktok.com/@kamso_ugc_creator?_r=1&_d=ec4aabki0e9666&sec_uid=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&share_author_id=7358384967619200005&sharer_language=en&source=h5_m&u_code=edhj0bf59c94ej&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7358384967619200005&share_link_id=1A413398-6D89-47BE-85BA-3F92A8A9EBD2&share_app_id=1233',
    'https://www.tiktok.com/@kamso_ugc_creator?_r=1&_d=ec4aabki0e9666&sec_uid=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&share_author_id=7358384967619200005&sharer_language=en&source=h5_m&u_code=edhj0bf59c94ej&ug_btm=b8727,b0&social_share_type=4&utm_source=copy&sec_user_id=MS4wLjABAAAAbuXJSkCf6KQvJpB39Aq5bJIVKIpNyRKTRTlA1QkTq38lAXZFVY9S0w90fXZEAOgs&tt_from=copy&utm_medium=ios&utm_campaign=client_share&enable_checksum=1&user_id=7358384967619200005&share_link_id=1A413398-6D89-47BE-85BA-3F92A8A9EBD2&share_app_id=1233',
    'Content creator specializing in Beauty. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Nwanozie Chiamaka tessy',
    'nwanoziechiamakatess',
    'chiamakanwanozie09@gmail.com',
    '+2349152632097',
    'Beauty',
    'Beauty',
    '["https://vm.tiktok.com/ZMSRD62d9/   https://vm.tiktok.com/ZMSRD6VW7/     https://www.instagram.com/reel/DJB_xPKIBpb/?igsh=MXRyenNpY2Z0bnR6bw=="]'::jsonb,
    'https://www.instagram.com/tessyexplorer/profilecard/?igsh=MTl6ZG9hN3ZseHN2aw==',
    'https://vm.tiktok.com/ZMSRD2sk2/',
    'Content creator specializing in Beauty. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Jesutoni Akoni',
    'jesutoniakoni',
    'ugcbyjesutoni@gmail.com',
    '+2348134817431',
    'Finance',
    'Finance',
    '[]'::jsonb,
    'https://www.instagram.com/ugcbyjesutoni',
    'https://www.tiktok.com/@ugcbyjesutoni_',
    'Content creator specializing in Finance. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Tuntamilore Tawak',
    'tuntamiloretawak',
    'ttawaq@gmail.com',
    '+2348097303020',
    'Fashion',
    'Fashion',
    '["tiktok.com/@tuntamilore"]'::jsonb,
    'instagram.com/tuntamilore',
    'tiktok.com/tuntamilore',
    'Content creator specializing in Fashion. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Praise Boldwill',
    'praiseboldwill',
    'ugcwithnenye@gmail.com',
    '+23422968979205',
    'Beauty',
    'Beauty',
    '[]'::jsonb,
    'https://instagram.com/ugcwithnenye',
    'https://tiktok.com/@ugcwithnenye',
    'Content creator specializing in Beauty. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Boluwatife mary',
    'boluwatifemary',
    'Boluwatifeogundola77@gmail.com',
    '+2349064420471',
    'Beauty',
    'Beauty',
    '["https://vm.tiktok.com/ZMSRVvETJ/"]'::jsonb,
    'https://www.instagram.com/bibi_brown01/profilecard/?igsh=ZDNjaWw4dHU4bnFx',
    'https://www.tiktok.com/@boluwatife_thecreator?_t=ZM-8wOalQAdhF1&_r=1',
    'Content creator specializing in Beauty. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Obi Chioma',
    'obichioma',
    'ugcoma@gmail.com',
    '+2349131069349',
    'Lifestyle',
    'Lifestyle',
    '[]'::jsonb,
    'https://www.instagram.com/oma.ugc?igsh=MTdtMmpwbjBycnY5dA%3D%3D&utm_source=qr',
    'https://www.tiktok.com/@oma_ugc?_t=8mPUdKvDdCQ&_r=1',
    'Content creator specializing in Lifestyle. Contact me for collaborations!',
    'active',
    'Nigeria'
),
(
    'Gabson Chidubem Mary-Immaculata',
    'gabsonchidubemmaryim',
    'theladybirdng@gmail.com',
    '+2347019762259',
    'General/Personal Brand',
    'General/Personal Brand',
    '[]'::jsonb,
    'https://www.instagram.com/_theladybird_/profilecard/?igsh=MTlpajBjaTZxamhvMA==  Here',
    'https://www.tiktok.com/@_theladybird_?_t=ZM-8wQO0gTbqz8&_r=1',
    'Content creator specializing in General/Personal Brand. Contact me for collaborations!',
    'active',
    'Nigeria'
); 